services:
  - type: web
    name: dentista-api
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 24
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
    disk:
      - name: database
        mountPath: /app/database
        sizeGB: 1
